package com.google.basic;

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class SumOfEvenValuedFibonacciNum {
	static int sum = 0;
	static int num1 = 1;
	static int num2 = 2;
	static int evenSum = 0;

	public static int sumOfEvenFibNum(int num) {
		for (int i = 1; i < num; i++) {
			
			sum = num1 + num2;
			num1 = num2;
			num2 = sum;
			if(sum < 4000000 & sum%2 == 0){
				evenSum = evenSum + sum;
				continue;
			}
			if(sum >= 4000000){
				
				break;
			}

		}

		return evenSum;
	}

}
